### ISSUE TITLE
Change Company information

### ISSUE THREAD

**Issue by MDaugaardDK** [LFM8787/PSADT.ToastNotification#3]
Hi!

Awesome extension, but i find it hard to figure out how to change Company information for the toast notification.

Could you give some direction on how to do that? :-)

**Comment by LFM8787** [comment]
Hi there, check the config XML file. It follows a similar PSADT structure to simplify.

Line 63 of xml file.

**Comment by dzaggiel** [comment]
Hey @LFM8787  i changed this line and still have PSADT.ToastNotification
`<DisplayName>CompanyName</DisplayName>`

**Comment by LFM8787** [comment]
It's volatile, simply logoff or reboot your PC (I know this is not the best way). This happens because you first executed the script without changing the value.

Or you cam navigate to the registry key by yourself and delete it, the extension checks it and writes the new value.

Next time remember to change it before :)

**Comment by dzaggiel** [comment]
@LFM8787 I did variable with company name in Deploy-Application and userd this variable in config. Its working but It does not add spaces between the text. How to solve it? Or can you provide me registry key which i should delete?
